data:
  property: aq
  filepath: "/workspace/data/AqueousSolu.csv"
  split: [random, accurate, scaffold]
  n_folds: 5
  data_seed: 42
ml:
  model: [mmb, mmb-ft, mmb-avg, ecfp]
  head: [hier, lin]
  n_epochs: 1,
  n_batch: 64,
  seed: 42
  


