params:
  - conf
  - conf/config
  # - params.yaml
  # - conf/config.yaml
  # - config.yaml
  # - ds/task: aq
  # - ds/split: scaffold
  # - ml/model: mmb
  # - ml/head: hier
    #- config.yaml
    #- cfg/ds
  

    #- cfg/data_cfg.json:property,split,data_seed
    #- cfg/model_cfg.json:

#   - split: random,accurate,scaffold
#   - model: mmb-lin,mmb-hier,mmb-ft-hier,mmb-ft-lin,mmb-avg,ecfp-hier,ecfp-lin

stages:
  split_data:
    # matrix:
    #   split: ${data.split}
    cmd: 
      # - echo "${item.ds.task} ${item.ds.split}"
      - echo "TEST ${ds}"
      - cd /workspace && echo "DATA ${ds.task} ${ds.split}"
      - mkdir -p data/${ds.task.task}/${ds.split.split}/
      - python3 scripts/split_data.py #${ds.task} ${ds.split}
      #        ${ds.task} ${ds.split}
    params:
      - ds.task
      - ds.split
    deps:
      # - data/AqueousSolu.csv
      # - cfg/data_config.json
      - src/dataloader.py
      - scripts/split_data.py
    outs:
      - data/${ds.task.task}/${ds.split.split}/

  train_model:
    cmd: 
      - mkdir -p out/${ds.task.task}/${ds.split.split}/${ml.model.model}-${ml.head.head}/{viz,model}
      - echo ${ml}
      - python3 scripts/train_model.py #${ds} ${ml}
            # ${ml.model} ${ml.head}
    params:
      - ml.model
      - ml.head
    # matrix:
    #   model: ${ml.model}
    #   head: ${ml.head}
    #   split: ${data.split}
    deps:
      - data/${ds.task.task}/${ds.split.split}/
      - src/model.py
      # - scripts/model_config.json
      # - scripts/train_model.py
    metrics:
      - out/${ds.task.task}/${ds.split.split}/${ml.model.model}-${ml.head.head}/metrics.json
    outs:
      - out/${ds.task.task}/${ds.split.split}/${ml.model.model}-${ml.head.head}/model/
      - out/${ds.task.task}/${ds.split.split}/${ml.model.model}-${ml.head.head}/best.pt

  # predict_aqueous:
  #   cmd: python3 scripts/predict_aqueous.py ${ml}
  #   params:
  #     - ml.model
  #     - ml.head
  #     - ml.xai
  #   deps:
  #     - src/model.py
  #     - scripts/predict_aqueous.py
  #     - data/${ds.task}/${ds.split}/
  #     - out/${ds.task}/${ds.split}/${ml.model}-${ml.head}/model/
  #   outs:
  #     - out/${ds.task}/${ds.split}/${ml.model}-${ml.head}/metrics.json 
  #     - out/${ds.task}/${ds.split}/${ml.model}-${ml.head}/preds.csv 
  #     - out/${ds.task}/${ds.split}/${ml.model}-${ml.head}/best.pt 
  #     - out/${ds.task}/${ds.split}/${ml.model}-${ml.head}/plots/

  explain_model:
    cmd:
      - mkdir -p out/${ds.task}/${ds.split}/${ml.model}-${ml.head}/viz
      - python3 scripts/explain_model.py ${ds} ${ml}
    deps:
      - scripts/explain_model.py
      - data/${ds.task}/${ds.split}/test.pkl
      - out/${ds.task}/${ds.split}/${ml.model}-${ml.head}/best.pt
      - src/maskedhead.py
    params:
      - ml.model
      - ml.head
      # - xai
    outs:
      - out/${ds.task}/${ds.split}/${ml.model}-${ml.head}/viz
      - out/${ds.task}/${ds.split}/${ml.model}-${ml.head}/parity_plot.png

  aq:
    cmd: echo "Finished full aqueous solubility pipeline"
    deps:
    - out/${ds.task}/${ds.split}/
    - out/${ds.task}/${ds.split}/${ml.model}-${ml.head}/best.pt
    - out/${ds.task}/${ds.split}/${ml.model}-${ml.head}/viz
