params:
  - params.yaml
#   - params.yaml
  # - conf
  # - conf/config
  # - conf/config.yaml
  # - config.yaml
  # - task: aq
  # - split: scaffold
  # - model: mmb
  # - head: hier
    #- config.yaml
    #- cfg/ds
  

    #- cfg/data_cfg.json:property,split,data_seed
    #- cfg/model_cfg.json:

#   - split: random,accurate,scaffold
#   - model: mmb-lin,mmb-hier,mmb-ft-hier,mmb-ft-lin,mmb-avg,ecfp-hier,ecfp-lin

stages:
  split_data:
    # matrix:
    #   split: ${data.split}
    cmd: 
      # - echo "${item.task} ${item.split}"
      - cd /workspace && echo "SPLIT DATA ${task} ${split}"
      - mkdir -p data/${task.task}/${split.split}/
      - python3 scripts/split_data.py #${task} ${split}
    params:
      - task
      - split
    deps:
      # - data/AqueousSolu.csv
      # - cfg/data_config.json
      - src/dataloader.py
      - scripts/split_data.py
    outs:
      - data/${task.task}/${split.split}/

  train_model:
    cmd: 
      - mkdir -p out/${task.task}/${split.split}/${model.model}-${head.head}/{viz,model}
      - echo "TRAIN ${model} ${head}"
      - python3 scripts/train_model.py #${task} ${split} ${model} ${head}
    params:
      - task
      - split
      - model
      - head
    # matrix:
    #   model: ${model}
    #   head: ${head}
    #   split: ${data.split}
    deps:
      - data/${task.task}/${split.split}/
      - src/model.py
      # - scripts/model_config.json
      # - scripts/train_model.py
    # metrics:
    #   - out/${task.task}/${split.split}/${model.model}-${head.head}/metrics.json
    outs:
      - out/${task.task}/${split.split}/${model.model}-${head.head}/model/
      - out/${task.task}/${split.split}/${model.model}-${head.head}/best.pt

  # predict_aqueous:
  #   cmd: python3 scripts/predict_aqueous.py ${
  #   params:
  #     - model
  #     - head
  #     - xai
  #   deps:
  #     - src/model.py
  #     - scripts/predict_aqueous.py
  #     - data/${task}/${split}/
  #     - out/${task}/${split}/${model}-${head}/model/
  #   outs:
  #     - out/${task}/${split}/${model}-${head}/metrics.json 
  #     - out/${task}/${split}/${model}-${head}/precsv 
  #     - out/${task}/${split}/${model}-${head}/best.pt 
  #     - out/${task}/${split}/${model}-${head}/plots/

  explain_model:
    cmd:
      - mkdir -p out/${task.task}/${split.split}/${model.model}-${head.head}/viz
      - python3 scripts/explain_model.py #${task} ${split} ${model} ${head} 
    deps:
      - scripts/explain_model.py
      - data/${task.task}/${split.split}/test.pkl
      - out/${task.task}/${split.split}/${model.model}-${head.head}/best.pt
      - src/maskedhead.py
    params:
      - task
      - split
      - model
      - head
      - xai
    outs:
      - out/${task.task}/${split.split}/${model.model}-${head.head}/viz
      - out/${task.task}/${split.split}/${model.model}-${head.head}/parity_plot.png

  aq:
    cmd: echo "Finished full aqueous solubility pipeline"
    deps:
    - out/${task.task}/${split.split}/
    - out/${task.task}/${split.split}/${model.model}-${head.head}/best.pt
    - out/${task.task}/${split.split}/${model.model}-${head.head}/viz
