task:
  task: aq
  property: aq
  loader: AqSolDataset
  filepath: /workspace/data/AqueousSolu.csv
  propname: logS_aq_avg
  smilesname: smiles solute
  plot_title: Aqueous solubility
  plot_propname: log(S)
split:
  split: accurate
  n_splits: 5
  split_frac: 0.9
  data_seed: 42
  color: r
  scale: false
model:
  model: ecfp2k
  nbits: 2048
  finetune: false
  n_batch: 48
  seed: 42
  n_epochs: 30
head:
  head: rf
  fit: sklearn
xai:
  model: ecfp
  xai: ecfp
  topk: 9
  mask: false
  cmap: div
