task:
  task: aq
  property: aq
  loader: AqSolDataset
  filepath: /workspace/data/AqueousSolu.csv
  propname: logS_aq_avg
  smilesname: smiles solute
  plot_title: Aqueous solubility
  plot_propname: log(S) log([mol/L])
split:
  split: accurate
  n_splits: 1
  split_frac: 0.9
  data_seed: 42
  color: r
  scale: false
model:
  model: mmb-ft-avg
  finetune: true
  n_batch: 48
  seed: 42
  n_epochs: 2
head:
  head: lin
xai:
  model: mmb-avg
  xai: shap
  mask: false
