task:
  task: aq
  property: aq
  filepath: /workspace/data/AqueousSolu.csv
  propname: logS_aq_avg
  smilesname: smiles solute
  plot_title: Aqueous solubility
  plot_propname: log(S) log([mol/L])
split:
  split: accurate
  n_splits: 5
  split_frac: 0.9
  data_seed: 42
  scaffold_k: 3
  color: r
model:
  model: mmb
  finetune: false
  xai: ours
  n_batch: 64
  seed: 42
  n_epochs: 30
head:
  head: hier
