ds:
  task: aq
  split: accurate
  n_splits: 5
  split_frac: 0.9
  scaffold_k: 3
  color: r
ml:
  model: mmb
  head: hier
  xai: ours
  n_batch: 64
  seed: 42
  n_epochs: 1
xai:
  method: ours
  fid: None

