task:
  task: cmc
  property: cmc
  loader: CMCDataset
  filepath: /workspace/data/cmcdata.csv
  propname: pCMC
  smilesname: SMILES
  plot_title: Critical micelle concentration
  plot_desc: p(CMC)
split:
  split: scaffold
  n_splits: 4
  split_frac: 0.9
  data_seed: 42
  scaffold_k: 3
  color: b
model:
  model: ecfp
  finetune: false
  xai: ecfp
  n_batch: 64
  seed: 42
  n_epochs: 50
  nbits: 512
head:
  head: lin
