task:
  task: sft
  property: sft
  loader: SFTDataset
  filepath: /workspace/data/MicellizationDataset.csv
  propname: AW_ST_CMC
  smilesname: SMILES
  plot_title: Surface tension at CMC
  plot_desc: ST@CMC
  plot_propname: Surface tension at CMC
split:
  split: random
  n_splits: 5
  split_frac: 0.9
  data_seed: 42
  color: g
model:
  model: ecfp
  nbits: 512
  finetune: false
  n_batch: 48
  seed: 42
  n_epochs: 30
head:
  head: hier
xai:
  model: ecfp
  xai: ecfp
  topk: 9
  mask: false
