task:
  task: aq
  property: aq
  loader: AqSolDataset
  filepath: /workspace/data/AqueousSolu.csv
  propname: logS_aq_avg
  smilesname: smiles solute
  plot_title: Aqueous solubility
  plot_propname: log(S) log([mol/L])
split:
  split: accurate
  n_splits: 3
  split_frac: 0.9
  data_seed: 42
  scaffold_k: 3
  color: r
model:
  model: ecfp
  nbits: 512
  finetune: false
  n_batch: 64
  seed: 42
  n_epochs: 50
head:
  head: hier
xai:
  mask: false
  nbits: 9
