task:
  task: aq
  property: aq
  loader: AqSolDataset
  filepath: /workspace/data/AqueousSolu.csv
  propname: logS_aq_avg
  smilesname: smiles solute
  plot_title: Aqueous solubility
  plot_propname: log(S) log([mol/L])
split:
  split: random
  n_splits: 5
  split_frac: 0.9
  data_seed: 42
  color: g
model:
  model: ecfp
  nbits: 512
  finetune: false
  n_batch: 48
  seed: 42
  n_epochs: 30
head:
  head: hier
xai:
  model: ecfp
  xai: ecfp
  topk: 9
  mask: false
