task:
  task: aq
  property: aq
  loader: AqSolDataset
  filepath: /workspace/data/AqueousSolu.csv
  propname: logS_aq_avg
  smilesname: smiles solute
  plot_title: Aqueous solubility
  plot_propname: log(S)
split:
  split: scaffold
  n_splits: 5
  split_frac: 0.9
  data_seed: 42
  scaffold_k: 3
  color: b
  scale: true
model:
  model: mmb-ft
  finetune: true
  n_batch: 48
  seed: 42
  n_epochs: 1
head:
  head: lin
  fit: model
xai:
  model: mmb
  xai: mmb
  mask: true
  sign: None
  save_heat: false
  cmap: None
