task:
  task: toy
  property: toy
  loader: ToyDataset
  filepath: /workspace/data/AqueousSolu.csv
  propname: carboncount
  smilesname: smiles solute
  plot_title: 'Toy test: Carbon count prediction'
  plot_propname: Number of carbon atoms
split:
  split: random
  n_splits: 5
  split_frac: 0.9
  data_seed: 42
  color: g
model:
  model: ecfp
  nbits: 2048
  finetune: false
  n_batch: 64
  seed: 42
  n_epochs: 30
head:
  head: lin
xai:
  model: ecfp
  xai: ecfp
  topk: 9
  mask: false
