task:
  task: aq
  property: aq
  loader: AqSolDataset
  filepath: /workspace/data/AqueousSolu.csv
  propname: logS_aq_avg
  smilesname: smiles solute
  plot_title: Aqueous solubility
  plot_propname: log(S) log([mol/L])
split:
  split: random
  n_splits: 5
  split_frac: 0.9
  data_seed: 42
  color: g
  scaffold_k: 3
model:
  model: ecfp
  finetune: false
  n_batch: 64
  seed: 42
  n_epochs: 50
  xai: ours
  nbits: 512
head:
  head: lin
xai:
  model: ecfp
  xai: ecfp
  mask: false
  sign: neg
  topk: 9
