task:
  task: aq
  property: aq
  loader: AqSolDataset
  filepath: /workspace/data/AqueousSolu.csv
  propname: logS_aq_avg
  smilesname: smiles solute
  plot_title: Aqueous solubility
  plot_propname: log(S)
split:
  split: accurate
  n_splits: 1
  split_frac: 0.9
  data_seed: 42
  color: r
  scale: true
model:
  model: ecfp
  nbits: 512
  finetune: false
  n_batch: 64
  seed: 42
  n_epochs: 1
head:
  head: svr
  fit: sklearn
xai:
  model: ecfp
  xai: ecfp
  topk: 9
  mask: false
  cmap: div
