task:
  task: aq
  property: aq
  loader: AqSolDataset
  filepath: /workspace/data/AqueousSolu.csv
  propname: logS_aq_avg
  smilesname: smiles solute
  plot_title: Aqueous solubility
  plot_propname: log(S) log([mol/L])
split:
  split: random
  n_splits: 2
  split_frac: 0.9
  data_seed: 42
  scaffold_k: 3
  color: 'y'
model:
  model: mmb
  finetune: false
  xai: ours
  n_batch: 64
  seed: 42
  n_epochs: 50
head:
  head: hier
xai:
  model: mmb
  mask: false
